create table tbl_filme(
    id number generated by default as identity,
    titulo varchar2(100),
    diretor varchar2(50),
    classificacao varchar2(20),
    genero varchar2(50),
    duracao number,
    lancamento date,
    primary key(id)
);

alter table tbl_filme add nota number(3,1);

insert into tbl_filme(titulo, diretor, classificacao, genero, duracao, lancamento, nota)
values('O Jogo da Imitação', 'Morten Tyldum', '12 anos', 'suspense biográfico', 114,
to_date('28-12-2014', 'DD-MM-YYYY'), 8.0);
