create table PERGUNTA(
    id number generated by default as identity,
    numero number,
    questao varchar2(300),
    primary key(id)
);

alter table PERGUNTA add constraint uniq_questao unique(questao)

create table RESPOSTA(
    id number generated by default as identity,
    respondente varchar2(50),
    valor varchar2(400),
    data date,
    id_pergunta number,
    foreign key(id_pergunta) references PERGUNTA(id)
);