create table tb_enquete(
    id number generated by default as identity,
    nome varchar2(100),
    primary key(id)
);

create table tb_pergunta(
    id number generated by default as identity,
    numero number,
    questao varchar2(200),
    tipo varchar2(50),
    enquete_id number,
    primary key(id),
    foreign key(enquete_id) references tb_enquete(id)
);

create table tb_item(
    pergunta_id number,
    nome varchar2(50),
    foreign key(pergunta_id) references tb_pergunta(id)
);

create table tb_resposta(
    id number generated by default as identity,
    usuario varchar2(100),
    data date,
    resposta varchar2(500),
    pergunta_id number,
    foreign key(pergunta_id) references tb_pergunta(id)
);






