create table tbs_pessoa(
    id number generated by default as identity,
    nome varchar2(100),
    telefone varchar2(20),
    cpf varchar2(15),
    nascimento date,
    sexo varchar2(20),
    primary key(id)
);

create table tbs_endereco(
    cep varchar2(15),
    logradouro varchar2(100),
    numero varchar2(10),
    complemento varchar2(20),
    bairro varchar2(20),
    municipio varchar2(30),
    id_pessoa number,
    foreign key(id_pessoa) references tbs_pessoa(id)
);





